version: '2'
services:
  eureka-server:
    image: eureka-server
    ports:
     - "8761:8761"
  fc-server:
    image: fc-server
    depends_on:
     - eureka-server
     - fca-server
    ports:
     - "9091:3333"
  fca-server:
    image: fca-server
    depends_on:
     - eureka-server
    ports:
     - "9090:2223"
